### ISSUE TITLE
자막 수정 요청

### ISSUE THREAD

**Issue by soo-yang** [TeamLab/introduction_to_python_TEAMLAB_MOOC#7]
교수님 영상을 확인해보니 1-1 영상의 자막이 8분 30초 부터 안나옵니다.
자막 파일을 다시 보내주실 수 있을까요?
그리고 3-5-1, 3-5-2 자막은 아직 안보내주신게 맞나요?

**Comment by blissray** [comment]
자막은 아래와 같이 문제 없이 나오는 거 같은데 srt 문제일까요?

https://www.youtube.com/watch?v=t84jQTwMFuE&list=PLBHVuYlKEkUJcXrgVu-bFx-One095BJ8I&index=3&t=14s

다시 다운로드 받아서 드릴까요?

**Comment by soo-yang** [comment]
네 다시 보내주시면 좋을것 같아요!

**Comment by blissray** [comment]
일단 1-1 송부드립니다.

--
*Sungchul Choi *
*Assistant Professor*Department of Industrial and Management Engineering
Gachon University, Seongnam, Republic of Korea
Office: +82-31-750-5804
G-Calendar: http://goo.gl/hqq7wt
Email: sc82.choi@gachon.ac.kr

**Comment by blissray** [comment]
이슈가 없는걸 확인되어 종료합니다.
